/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ReformaTributariaRouteImport } from './routes/reforma-tributaria'
import { Route as OmnilinkRouteImport } from './routes/omnilink'
import { Route as ObrigacoesRouteImport } from './routes/obrigacoes'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntradasIndexRouteImport } from './routes/entradas.index'
import { Route as EntradasRelatoriosRouteImport } from './routes/entradas.relatorios'
import { Route as EntradasEstoqueRouteImport } from './routes/entradas.estoque'
import { Route as EntradasComprasRouteImport } from './routes/entradas.compras'
import { Route as ApiPublicWebhooksCanalIdRouteImport } from './routes/api/public/webhooks.$canalId'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformaTributariaRoute = ReformaTributariaRouteImport.update({
  id: '/reforma-tributaria',
  path: '/reforma-tributaria',
  getParentRoute: () => rootRouteImport,
} as any)
const OmnilinkRoute = OmnilinkRouteImport.update({
  id: '/omnilink',
  path: '/omnilink',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigacoesRoute = ObrigacoesRouteImport.update({
  id: '/obrigacoes',
  path: '/obrigacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasIndexRoute = EntradasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntradasRoute,
} as any)
const EntradasRelatoriosRoute = EntradasRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => EntradasRoute,
} as any)
const EntradasEstoqueRoute = EntradasEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => EntradasRoute,
} as any)
const EntradasComprasRoute = EntradasComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => EntradasRoute,
} as any)
const ApiPublicWebhooksCanalIdRoute =
  ApiPublicWebhooksCanalIdRouteImport.update({
    id: '/api/public/webhooks/$canalId',
    path: '/api/public/webhooks/$canalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/entradas': typeof EntradasRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fiscal': typeof FiscalRoute
  '/obrigacoes': typeof ObrigacoesRoute
  '/omnilink': typeof OmnilinkRoute
  '/reforma-tributaria': typeof ReformaTributariaRoute
  '/vendas': typeof VendasRoute
  '/entradas/compras': typeof EntradasComprasRoute
  '/entradas/estoque': typeof EntradasEstoqueRoute
  '/entradas/relatorios': typeof EntradasRelatoriosRoute
  '/entradas/': typeof EntradasIndexRoute
  '/api/public/webhooks/$canalId': typeof ApiPublicWebhooksCanalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fiscal': typeof FiscalRoute
  '/obrigacoes': typeof ObrigacoesRoute
  '/omnilink': typeof OmnilinkRoute
  '/reforma-tributaria': typeof ReformaTributariaRoute
  '/vendas': typeof VendasRoute
  '/entradas/compras': typeof EntradasComprasRoute
  '/entradas/estoque': typeof EntradasEstoqueRoute
  '/entradas/relatorios': typeof EntradasRelatoriosRoute
  '/entradas': typeof EntradasIndexRoute
  '/api/public/webhooks/$canalId': typeof ApiPublicWebhooksCanalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/entradas': typeof EntradasRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fiscal': typeof FiscalRoute
  '/obrigacoes': typeof ObrigacoesRoute
  '/omnilink': typeof OmnilinkRoute
  '/reforma-tributaria': typeof ReformaTributariaRoute
  '/vendas': typeof VendasRoute
  '/entradas/compras': typeof EntradasComprasRoute
  '/entradas/estoque': typeof EntradasEstoqueRoute
  '/entradas/relatorios': typeof EntradasRelatoriosRoute
  '/entradas/': typeof EntradasIndexRoute
  '/api/public/webhooks/$canalId': typeof ApiPublicWebhooksCanalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/entradas'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/obrigacoes'
    | '/omnilink'
    | '/reforma-tributaria'
    | '/vendas'
    | '/entradas/compras'
    | '/entradas/estoque'
    | '/entradas/relatorios'
    | '/entradas/'
    | '/api/public/webhooks/$canalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastros'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/obrigacoes'
    | '/omnilink'
    | '/reforma-tributaria'
    | '/vendas'
    | '/entradas/compras'
    | '/entradas/estoque'
    | '/entradas/relatorios'
    | '/entradas'
    | '/api/public/webhooks/$canalId'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/entradas'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/obrigacoes'
    | '/omnilink'
    | '/reforma-tributaria'
    | '/vendas'
    | '/entradas/compras'
    | '/entradas/estoque'
    | '/entradas/relatorios'
    | '/entradas/'
    | '/api/public/webhooks/$canalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRoute
  EntradasRoute: typeof EntradasRouteWithChildren
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FiscalRoute: typeof FiscalRoute
  ObrigacoesRoute: typeof ObrigacoesRoute
  OmnilinkRoute: typeof OmnilinkRoute
  ReformaTributariaRoute: typeof ReformaTributariaRoute
  VendasRoute: typeof VendasRoute
  ApiPublicWebhooksCanalIdRoute: typeof ApiPublicWebhooksCanalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma-tributaria': {
      id: '/reforma-tributaria'
      path: '/reforma-tributaria'
      fullPath: '/reforma-tributaria'
      preLoaderRoute: typeof ReformaTributariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omnilink': {
      id: '/omnilink'
      path: '/omnilink'
      fullPath: '/omnilink'
      preLoaderRoute: typeof OmnilinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigacoes': {
      id: '/obrigacoes'
      path: '/obrigacoes'
      fullPath: '/obrigacoes'
      preLoaderRoute: typeof ObrigacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas/': {
      id: '/entradas/'
      path: '/'
      fullPath: '/entradas/'
      preLoaderRoute: typeof EntradasIndexRouteImport
      parentRoute: typeof EntradasRoute
    }
    '/entradas/relatorios': {
      id: '/entradas/relatorios'
      path: '/relatorios'
      fullPath: '/entradas/relatorios'
      preLoaderRoute: typeof EntradasRelatoriosRouteImport
      parentRoute: typeof EntradasRoute
    }
    '/entradas/estoque': {
      id: '/entradas/estoque'
      path: '/estoque'
      fullPath: '/entradas/estoque'
      preLoaderRoute: typeof EntradasEstoqueRouteImport
      parentRoute: typeof EntradasRoute
    }
    '/entradas/compras': {
      id: '/entradas/compras'
      path: '/compras'
      fullPath: '/entradas/compras'
      preLoaderRoute: typeof EntradasComprasRouteImport
      parentRoute: typeof EntradasRoute
    }
    '/api/public/webhooks/$canalId': {
      id: '/api/public/webhooks/$canalId'
      path: '/api/public/webhooks/$canalId'
      fullPath: '/api/public/webhooks/$canalId'
      preLoaderRoute: typeof ApiPublicWebhooksCanalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EntradasRouteChildren {
  EntradasComprasRoute: typeof EntradasComprasRoute
  EntradasEstoqueRoute: typeof EntradasEstoqueRoute
  EntradasRelatoriosRoute: typeof EntradasRelatoriosRoute
  EntradasIndexRoute: typeof EntradasIndexRoute
}

const EntradasRouteChildren: EntradasRouteChildren = {
  EntradasComprasRoute: EntradasComprasRoute,
  EntradasEstoqueRoute: EntradasEstoqueRoute,
  EntradasRelatoriosRoute: EntradasRelatoriosRoute,
  EntradasIndexRoute: EntradasIndexRoute,
}

const EntradasRouteWithChildren = EntradasRoute._addFileChildren(
  EntradasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRoute,
  EntradasRoute: EntradasRouteWithChildren,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  FiscalRoute: FiscalRoute,
  ObrigacoesRoute: ObrigacoesRoute,
  OmnilinkRoute: OmnilinkRoute,
  ReformaTributariaRoute: ReformaTributariaRoute,
  VendasRoute: VendasRoute,
  ApiPublicWebhooksCanalIdRoute: ApiPublicWebhooksCanalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
